name: Deploy master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Copy example properties
        run: cp common/src/main/resources/properties/server.properties.example common/src/main/resources/properties/server.properties

      - name: Install requests
        run: python3 -m pip install requests

      - name: Run Python deploy script
        run: python3 ./deploy.py

      - name: Build the damn thing
        run: mvn clean spotless:check install

      - name: Generate deployment package
        run: zip build.zip Dockerfile service/target/service-1.0-SNAPSHOT-jar-with-dependencies.jar

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: c4c-internal
          environment_name: c4c-backend-scaffold
          region: us-east-2
          deployment_package: build.zip